# image: debian:bookworm

variables:
  GIT_DEPTH: "1"
  GIT_STRATEGY: none #fetch
  GIT_SUBMODULE_STRATEGY: none
  GIT_CONFIG_COUNT: "1"
  GIT_CONFIG_KEY_0: "safe.directory"
  GIT_CONFIG_VALUE_0: "*"
  GIT_SSL_NO_VERIFY: "1"
  DEBIAN_FRONTEND: noninteractive
  FF_USE_FASTZIP: true
  ARTIFACT_COMPRESSION_LEVEL: "slowest"
  CACHE_COMPRESSION_LEVEL: "slowest"


default:
  tags: [testbed-ci-runner]
  before_script:
    # Handle sudo
    # - |
    #   mkdir -p /usr/local/bin
    #   cat > /usr/local/bin/sudo <<'EOF'
    #   #!/usr/bin/env bash
    #   exec "$@"
    #   EOF
    #   chmod +x /usr/local/bin/sudo
    #   hash -r

    # General setup
    - echo 'debconf debconf/frontend select Noninteractive' | sudo debconf-set-selections || true
    - export DEBIAN_FRONTEND=noninteractive
    - cd "$CI_PROJECT_DIR"
    - pwd
    - tree . -d
  after_script:
    - sudo chown -R "$USER:$USER" "$CI_PROJECT_DIR" || true

stages:
  - initialization
  - testbed_1
  - testbed_2
  - finalization

################################################################################
############################### INITIALIZATION #################################
################################################################################

pre_install_cleanup:
  stage: initialization
  interruptible: true
  resource_group: testbed
  variables:
    GIT_STRATEGY: none
  allow_failure: true
  script:
    # Uninstall components then remove files from previous runs
    - |
      if [[ -f "5G_Core_Network/options.yaml" && -f "full_uninstall.sh" && -f "OpenAirInterface_Testbed/full_uninstall.sh" ]]; then
        # Testbed 1
        sed -i -E 's/^core_to_use:.*/core_to_use: open5gs/' 5G_Core_Network/options.yaml
        ./full_uninstall.sh
        
        # Testbed 2
        sed -i -E 's/^core_to_use:.*/core_to_use: 5gdeploy-open5gs/' 5G_Core_Network/options.yaml
        cd OpenAirInterface_Testbed
        ./full_uninstall.sh
        cd ..
        
        sed -i -E 's/^core_to_use:.*/core_to_use: open5gs/' 5G_Core_Network/options.yaml
      else
        echo "Repositories don't exist for uninstall_all_components, skipping."
      fi
    - sudo rm -rf * && sudo rm -rf .git*
    # Get apt into a clean state before testbed setup
    - sudo rm -f /var/lib/dpkg/lock-frontend /var/lib/dpkg/lock || true
    - sudo dpkg --configure -a || true
    - |
      if dpkg -s mongosh >/dev/null 2>&1 || ls /var/lib/dpkg/info/mongosh* >/dev/null 2>&1; then
        echo "Purging broken mongosh package..."
        sudo dpkg --remove --force-remove-reinstreq mongosh || true
        sudo dpkg --purge mongosh || true
        sudo rm -f /var/lib/dpkg/info/mongosh.* || true
      fi
    - sudo apt-get -y -f install || true
    - sudo apt-get update
    - sudo apt-get install -y sudo bash grep coreutils curl wget git gnupg lsb-release tree ca-certificates
    - sudo apt-get install -y --no-install-recommends tzdata
    - sudo update-ca-certificates || true

################################################################################
########################### TESTBED 1 INSTALLATION #############################
################################################################################

open5gs_srsran_oran_sc_ric_setup:
  stage: testbed_1
  interruptible: true
  resource_group: testbed
  needs: [pre_install_cleanup]
  variables:
    GIT_STRATEGY: clone
  script:
    - echo -e "\e[0Ksection_start:$(date +%s):open5gs_configure[collapsed=true]\r\e[0KConfigure Open5GS"
    - echo "***************************** CI Install Open5GS *******************************"
    - cd OpenAirInterface_Testbed/5G_Core_Network
    # Configure the core to use: open5gs
    - "sed -i -E 's/^core_to_use:.*/core_to_use: open5gs/' options.yaml"
    # Disable systemctl so that components are direct processes running in background
    - "sed -i -E 's/^use_systemctl:.*/use_systemctl: false/' options.yaml"
    - cd ../..
    - echo -e "\e[0Ksection_end:$(date +%s):open5gs_configure\r\e[0K"

    - echo -e "\e[0Ksection_start:$(date +%s):o-ran-sc_near-rt-ric_install[collapsed=true]\r\e[0KInstall O-RAN SC Near-RT RIC"
    - echo "********************** CI Install O-RAN SC Near-RT RIC *************************"
    - cd RAN_Intelligent_Controllers/Near-Real-Time-RIC
    - ./full_install.sh
    - cd ../..
    - echo -e "\e[0Ksection_end:$(date +%s):o-ran-sc_near-rt-ric_install\r\e[0K"

    - echo -e "\e[0Ksection_start:$(date +%s):open5gs_install[collapsed=true]\r\e[0KInstall Open5GS"
    - echo "***************************** CI Install Open5GS *******************************"
    - cd OpenAirInterface_Testbed/5G_Core_Network
    - ./full_install.sh
    - cd ../..
    - echo -e "\e[0Ksection_end:$(date +%s):open5gs_install\r\e[0K"

    - echo -e "\e[0Ksection_start:$(date +%s):srsran_ue_install[collapsed=true]\r\e[0KInstall srsRAN_4G UE"
    - echo "**************************** CI Install srsRAN UE ******************************"
    - cd User_Equipment
    - ./full_install.sh
    - cd ..
    - echo -e "\e[0Ksection_end:$(date +%s):srsran_ue_install\r\e[0K"
    
    - echo -e "\e[0Ksection_start:$(date +%s):srsran_gnb_install[collapsed=true]\r\e[0KInstall srsRAN_Project gNB"
    - echo "*************************** CI Install srsRAN gNB ******************************"
    - cd Next_Generation_Node_B
    - ./full_install.sh
    - cd ..
    - echo -e "\e[0Ksection_end:$(date +%s):srsran_gnb_install\r\e[0K"
    
    # - echo -e "\e[0Ksection_start:$(date +%s):o-ran-sc_near-rt-ric_install[collapsed=true]\r\e[0KInstall O-RAN SC Near-RT RIC"
    # - echo "********************** CI Install O-RAN SC Near-RT RIC *************************"
    # - cd RAN_Intelligent_Controllers/Near-Real-Time-RIC
    # - ./full_install.sh
    # - cd ../..
    # - echo -e "\e[0Ksection_end:$(date +%s):o-ran-sc_near-rt-ric_install\r\e[0K"

    - echo -e "\e[0Ksection_start:$(date +%s):testbed_2_configuration[collapsed=true]\r\e[0KTestbed 2 Configuration"
    - echo "****************************** CI Configuration ********************************"
    - ./generate_configurations.sh --disable-e2-term
    - echo -e "\e[0Ksection_end:$(date +%s):testbed_2_configuration\r\e[0K"

      ############################ TODO: END-TO-END TESTS ############################

    - echo -e "\e[0Ksection_start:$(date +%s):open5gs_uninstall[collapsed=true]\r\e[0KUninstall Open5GS"
    - echo "**************************** CI Uninstall Open5GS ******************************"
    - cd 5G_Core_Network
    - ./full_uninstall.sh bypass_confirmation
    - cd ..
    - echo -e "\e[0Ksection_end:$(date +%s):open5gs_uninstall\r\e[0K"

    - echo -e "\e[0Ksection_start:$(date +%s):srsran_ue_uninstall[collapsed=true]\r\e[0KUninstall srsRAN_4G UE"
    - echo "*************************** CI Uninstall srsRAN UE *****************************"
    - cd User_Equipment
    - ./full_uninstall.sh bypass_confirmation
    - cd ..
    - echo -e "\e[0Ksection_end:$(date +%s):srsran_ue_uninstall\r\e[0K"

    - echo -e "\e[0Ksection_start:$(date +%s):srsran_gnb_uninstall[collapsed=true]\r\e[0KUninstall srsRAN_Project gNB"
    - echo "*************************** CI Uninstall srsRAN gNB ****************************"
    - cd Next_Generation_Node_B
    - ./full_uninstall.sh bypass_confirmation
    - cd ..
    - echo -e "\e[0Ksection_end:$(date +%s):srsran_gnb_uninstall\r\e[0K"
    
    - echo -e "\e[0Ksection_start:$(date +%s):o-ran-sc_near-rt-ric_uninstall[collapsed=true]\r\e[0KUninstall O-RAN SC Near-RT RIC"
    - echo "********************* CI Uninstall O-RAN SC Near-RT RIC ************************"
    - cd RAN_Intelligent_Controllers/Near-Real-Time-RIC
    - ./full_uninstall.sh bypass_confirmation
    - cd ../..
    - echo -e "\e[0Ksection_end:$(date +%s):o-ran-sc_near-rt-ric_uninstall\r\e[0K"
  retry: 2


################################################################################
########################### TESTBED 2 INSTALLATION #############################
################################################################################

openairinterface_flexric_5gdeploy_setup:
  stage: testbed_2
  interruptible: true
  resource_group: testbed
  needs: [open5gs_srsran_oran_sc_ric_setup]
  variables:
    GIT_STRATEGY: clone
  script:

    - echo -e "\e[0Ksection_start:$(date +%s):5gdeploy_configure[collapsed=true]\r\e[0KConfigure 5gdeploy"
    - echo "***************************** CI Install Open5GS *******************************"
    - cd OpenAirInterface_Testbed/5G_Core_Network
    # Configure the core to use: 5gdeploy-open5gs
    - "sed -i -E 's/^core_to_use:.*/core_to_use: 5gdeploy-open5gs/' options.yaml"
    # Disable systemctl so that components are direct processes running in background
    - "sed -i -E 's/^use_systemctl:.*/use_systemctl: false/' options.yaml"
    - cd ../..
    - echo -e "\e[0Ksection_end:$(date +%s):5gdeploy_configure\r\e[0K"

    - echo -e "\e[0Ksection_start:$(date +%s):oai_ue_install[collapsed=true]\r\e[0KInstall OpenAirInterface UE"
    - echo "***************************** CI Install OAI UE ********************************"
    - cd OpenAirInterface_Testbed/User_Equipment
    - ./full_install.sh
    - cd ../..
    - echo -e "\e[0Ksection_end:$(date +%s):oai_ue_install\r\e[0K"

    - echo -e "\e[0Ksection_start:$(date +%s):oai_gnb_install[collapsed=true]\r\e[0KInstall OpenAirInterface gNB"
    - echo "***************************** CI Install OAI gNB *******************************"
    - cd OpenAirInterface_Testbed/Next_Generation_Node_B
    - ./full_install.sh
    - cd ../..
    - echo -e "\e[0Ksection_end:$(date +%s):oai_gnb_install\r\e[0K"

    - echo -e "\e[0Ksection_start:$(date +%s):flexric_install[collapsed=true]\r\e[0KInstall FlexRIC"
    - echo "***************************** CI Install FlexRIC *******************************"
    - cd OpenAirInterface_Testbed/RAN_Intelligent_Controllers/Flexible-RIC
    - ./full_install.sh
    - cd ../../..
    - echo -e "\e[0Ksection_end:$(date +%s):flexric_install\r\e[0K"
    
    - echo -e "\e[0Ksection_start:$(date +%s):5gdeploy_install[collapsed=true]\r\e[0KInstall 5G Deployment Helper (5gdeploy)"
    - echo "********************** CI Install 5G Deployment Helper *************************"
    - cd 5G_Core_Network
    - ./full_install.sh
    - cd ..
    - echo -e "\e[0Ksection_end:$(date +%s):5gdeploy_install\r\e[0K"

    - echo -e "\e[0Ksection_start:$(date +%s):testbed_1_configuration[collapsed=true]\r\e[0KTestbed 1 Configuration"
    - echo "****************************** CI Configuration ********************************"
    - cd OpenAirInterface_Testbed
    - ./generate_configurations.sh
    - cd ..
    - echo -e "\e[0Ksection_end:$(date +%s):testbed_1_configuration\r\e[0K"

      ############################ TODO: END-TO-END TESTS ############################

    - echo -e "\e[0Ksection_start:$(date +%s):oai_ue_uninstall[collapsed=true]\r\e[0KUninstall OpenAirInterface UE"
    - echo "***************************** CI Uninstall OAI UE ******************************"
    - cd OpenAirInterface_Testbed/User_Equipment
    - ./full_uninstall.sh bypass_confirmation
    - cd ../..
    - echo -e "\e[0Ksection_end:$(date +%s):oai_ue_uninstall\r\e[0K"

    - echo -e "\e[0Ksection_start:$(date +%s):oai_gnb_uninstall[collapsed=true]\r\e[0KUninstall OpenAirInterface gNB"
    - echo "***************************** CI Uninstall OAI gNB *****************************"
    - cd OpenAirInterface_Testbed/Next_Generation_Node_B
    - ./full_uninstall.sh bypass_confirmation
    - cd ../..
    - echo -e "\e[0Ksection_end:$(date +%s):oai_gnb_uninstall\r\e[0K"

    - echo -e "\e[0Ksection_start:$(date +%s):flexric_uninstall[collapsed=true]\r\e[0KUninstall FlexRIC"
    - echo "***************************** CI Uninstall FlexRIC *****************************"
    - cd OpenAirInterface_Testbed/RAN_Intelligent_Controllers/Flexible-RIC
    - ./full_uninstall.sh bypass_confirmation
    - cd ../../..
    - echo -e "\e[0Ksection_end:$(date +%s):flexric_uninstall\r\e[0K"
    
    - echo -e "\e[0Ksection_start:$(date +%s):5gdeploy_uninstall[collapsed=true]\r\e[0KUninstall 5G Deployment Helper (5gdeploy)"
    - echo "********************* CI Uninstall 5G Deployment Helper ************************"
    - cd 5G_Core_Network
    - ./full_uninstall.sh bypass_confirmation
    - cd ..
    - echo -e "\e[0Ksection_end:$(date +%s):5gdeploy_uninstall\r\e[0K"
  retry: 2

################################################################################
################################ FINALIZATION ##################################
################################################################################

post_install_cleanup:
  stage: finalization
  interruptible: true
  resource_group: testbed
  needs:
    - job: open5gs_srsran_oran_sc_ric_setup
      optional: true
    - job: openairinterface_flexric_5gdeploy_setup
      optional: true
  variables:
    GIT_STRATEGY: none
  allow_failure: true
  script:
    # Uninstall components then remove files from this run
    - |
      if [[ -f "5G_Core_Network/options.yaml" && -f "full_uninstall.sh" && -f "OpenAirInterface_Testbed/full_uninstall.sh" ]]; then
        # Testbed 1
        sed -i -E 's/^core_to_use:.*/core_to_use: open5gs/' 5G_Core_Network/options.yaml
        ./full_uninstall.sh
        # Testbed 2
        sed -i -E 's/^core_to_use:.*/core_to_use: 5gdeploy-open5gs/' 5G_Core_Network/options.yaml
        cd OpenAirInterface_Testbed
        ./full_uninstall.sh
        cd ..
        sed -i -E 's/^core_to_use:.*/core_to_use: open5gs/' 5G_Core_Network/options.yaml
      else
        echo "Repositories don't exist for uninstall_all_components, skipping."
      fi
    - sudo rm -rf * && sudo rm -rf .git*
  retry: 2
