REM NIST-developed software is provided by NIST as a public service. You may use,
REM copy, and distribute copies of the software in any medium, provided that you
REM keep intact this entire notice. You may improve, modify, and create derivative
REM works of the software or any portion of the software, and you may copy and
REM distribute such modifications or works. Modified works should carry a notice
REM stating that you changed the software and should note the date and nature of
REM any such change. Please explicitly acknowledge the National Institute of
REM Standards and Technology as the source of the software.
REM
REM NIST-developed software is expressly provided AS IS. NIST MAKES NO WARRANTY
REM OF ANY KIND, EXPRESS, IMPLIED, IN FACT, OR ARISING BY OPERATION OF LAW,
REM INCLUDING, WITHOUT LIMITATION, THE IMPLIED WARRANTY OF MERCHANTABILITY,
REM FITNESS FOR A PARTICULAR PURPOSE, NON-INFRINGEMENT, AND DATA ACCURACY. NIST
REM NEITHER REPRESENTS NOR WARRANTS THAT THE OPERATION OF THE SOFTWARE WILL BE
REM UNINTERRUPTED OR ERROR-FREE, OR THAT ANY DEFECTS WILL BE CORRECTED. NIST DOES
REM NOT WARRANT OR MAKE ANY REPRESENTATIONS REGARDING THE USE OF THE SOFTWARE OR
REM THE RESULTS THEREOF, INCLUDING BUT NOT LIMITED TO THE CORRECTNESS, ACCURACY,
REM RELIABILITY, OR USEFULNESS OF THE SOFTWARE.
REM
REM You are solely responsible for determining the appropriateness of using and
REM distributing the software and you assume all risks associated with its use,
REM including but not limited to the risks and costs of program errors, compliance
REM with applicable laws, damage to or loss of data, programs or equipment, and
REM the unavailability or interruption of operation. This software is not intended
REM to be used in any situation where a failure could cause risk of injury or
REM damage to property. The software developed by NIST employees is not subject to
REM copyright protection within the United States.

@echo off

REM This is an automatically generated script to download the testbed repositories to analyze the source code without requiring a full testbed build and installation.
REM WARNING: Please do not edit this file manually since it is overwritten with the script: ./Additional_Scripts/generate_download_dependency_repositories.bat.sh

echo Script: %~f0...

REM Change to the parent directory of the script
cd %~dp0..
if exist "5G_Core_Network\open5gs" rmdir /s /q "5G_Core_Network\open5gs"
cd 5G_Core_Network
git clone https://github.com/open5gs/open5gs.git
cd open5gs
git checkout 52ca325ed5b11104e2a4b77a1aacb7e44af01ab5
cd ..\..

cd %~dp0..
if exist "User_Equipment\srsRAN_4G" rmdir /s /q "User_Equipment\srsRAN_4G"
cd User_Equipment
git clone https://github.com/srsran/srsRAN_4G.git
cd srsRAN_4G
git checkout ec29b0c1ff79cebcbe66caa6d6b90778261c42b8
cd ..\..

cd %~dp0..
if exist "User_Equipment\libzmq" rmdir /s /q "User_Equipment\libzmq"
cd User_Equipment
git clone https://github.com/zeromq/libzmq.git
cd libzmq
git checkout 3e5ce5c1cd75bd93b2ab51d98e0239eb8628b953
cd ..\..

cd %~dp0..
if exist "User_Equipment\czmq" rmdir /s /q "User_Equipment\czmq"
cd User_Equipment
git clone https://github.com/zeromq/czmq.git
cd czmq
git checkout 1786a2dcbfc4af94456615acc1d0f8358f2aadce
cd ..\..

cd %~dp0..
if exist "Next_Generation_Node_B\srsRAN_Project" rmdir /s /q "Next_Generation_Node_B\srsRAN_Project"
cd Next_Generation_Node_B
git clone https://github.com/srsran/srsRAN_Project.git
cd srsRAN_Project
git checkout 920ee6ecebfdfc8595165d4b42ebafca630854f7
cd ..\..

cd %~dp0..
if exist "RAN_Intelligent_Controllers\Near-Real-Time-RIC\ric-dep" rmdir /s /q "RAN_Intelligent_Controllers\Near-Real-Time-RIC\ric-dep"
cd RAN_Intelligent_Controllers\Near-Real-Time-RIC
git clone https://gerrit.o-ran-sc.org/r/ric-plt/ric-dep.git
cd ric-dep
git checkout 33b5940a15ea852d47f73521295eef53d295b7fd
cd ..\..\..

cd %~dp0..
if exist "RAN_Intelligent_Controllers\Near-Real-Time-RIC\e2-interface" rmdir /s /q "RAN_Intelligent_Controllers\Near-Real-Time-RIC\e2-interface"
cd RAN_Intelligent_Controllers\Near-Real-Time-RIC
git clone https://gerrit.o-ran-sc.org/r/sim/e2-interface.git
cd e2-interface
git checkout da6f82f286cdbb38af1178f82f85877b12c2f85b
cd ..\..\..

cd %~dp0..
if exist "RAN_Intelligent_Controllers\Near-Real-Time-RIC\appmgr" rmdir /s /q "RAN_Intelligent_Controllers\Near-Real-Time-RIC\appmgr"
cd RAN_Intelligent_Controllers\Near-Real-Time-RIC
git clone https://gerrit.o-ran-sc.org/r/ric-plt/appmgr.git
cd appmgr
git checkout 4c05932dce72e98db23eaff2b72b58816e1f2d55
cd ..\..\..

cd RAN_Intelligent_Controllers\Near-Real-Time-RIC
mkdir xApps
cd ..\..

cd %~dp0..
if exist "RAN_Intelligent_Controllers\Near-Real-Time-RIC\xApps\hw-go" rmdir /s /q "RAN_Intelligent_Controllers\Near-Real-Time-RIC\xApps\hw-go"
cd RAN_Intelligent_Controllers\Near-Real-Time-RIC\xApps
git clone https://gerrit.o-ran-sc.org/r/ric-app/hw-go.git
cd hw-go
git checkout 3a0d348e429ea0f3f3d2a1d5eb54ec8758d1a262
cd ..\..\..\..

cd %~dp0..
if exist "RAN_Intelligent_Controllers\Near-Real-Time-RIC\xApps\hw-python" rmdir /s /q "RAN_Intelligent_Controllers\Near-Real-Time-RIC\xApps\hw-python"
cd RAN_Intelligent_Controllers\Near-Real-Time-RIC\xApps
git clone https://gerrit.o-ran-sc.org/r/ric-app/hw-python.git
cd ..\..\..

cd %~dp0..
if exist "RAN_Intelligent_Controllers\Near-Real-Time-RIC\xApps\hw-rust" rmdir /s /q "RAN_Intelligent_Controllers\Near-Real-Time-RIC\xApps\hw-rust"
cd RAN_Intelligent_Controllers\Near-Real-Time-RIC\xApps
git clone https://gerrit.o-ran-sc.org/r/ric-app/hw-rust.git
cd ..\..\..

cd %~dp0..
if exist "RAN_Intelligent_Controllers\Near-Real-Time-RIC\xApps\kpimon-go" rmdir /s /q "RAN_Intelligent_Controllers\Near-Real-Time-RIC\xApps\kpimon-go"
cd RAN_Intelligent_Controllers\Near-Real-Time-RIC\xApps
git clone https://gerrit.o-ran-sc.org/r/ric-app/kpimon-go.git
cd kpimon-go
git checkout 8bbbbbb90093db01f88820de755bce0ee2189c88
cd ..\..\..\..

cd %~dp0..
if exist "RAN_Intelligent_Controllers\Near-Real-Time-RIC\xApps\ad-cell" rmdir /s /q "RAN_Intelligent_Controllers\Near-Real-Time-RIC\xApps\ad-cell"
cd RAN_Intelligent_Controllers\Near-Real-Time-RIC\xApps
git clone https://gerrit.o-ran-sc.org/r/ric-app/ad-cell.git
cd ad-cell
git checkout f1338a030f6c2c5a6ab2a970c0fe964c92aafa8f
cd ..\..\..\..

cd %~dp0..
if exist "RAN_Intelligent_Controllers\Near-Real-Time-RIC\xApps\ad" rmdir /s /q "RAN_Intelligent_Controllers\Near-Real-Time-RIC\xApps\ad"
cd RAN_Intelligent_Controllers\Near-Real-Time-RIC\xApps
git clone https://gerrit.o-ran-sc.org/r/ric-app/ad.git
cd ad
git checkout f9f97b8c682d890395e3de5a56450ebb04a5630b
cd ..\..\..\..

cd %~dp0..
if exist "RAN_Intelligent_Controllers\Near-Real-Time-RIC\xApps\qp" rmdir /s /q "RAN_Intelligent_Controllers\Near-Real-Time-RIC\xApps\qp"
cd RAN_Intelligent_Controllers\Near-Real-Time-RIC\xApps
git clone https://gerrit.o-ran-sc.org/r/ric-app/qp.git
cd qp
git checkout 47a35cafc3f90aed8b6fa711c37b131f06061ca6
cd ..\..\..\..

cd %~dp0..
if exist "RAN_Intelligent_Controllers\Near-Real-Time-RIC\xApps\rc" rmdir /s /q "RAN_Intelligent_Controllers\Near-Real-Time-RIC\xApps\rc"
cd RAN_Intelligent_Controllers\Near-Real-Time-RIC\xApps
git clone https://gerrit.o-ran-sc.org/r/ric-app/rc.git
cd rc
git checkout a2282eedc9e32f60298bf530456ad367bef0824b
cd ..\..\..\..

cd %~dp0..
if exist "RAN_Intelligent_Controllers\Near-Real-Time-RIC\xApps\ts" rmdir /s /q "RAN_Intelligent_Controllers\Near-Real-Time-RIC\xApps\ts"
cd RAN_Intelligent_Controllers\Near-Real-Time-RIC\xApps
git clone https://gerrit.o-ran-sc.org/r/ric-app/ts.git
cd ts
git checkout 19e169b2e81a0dbaf3d9dc526de0415cc995ee8b
cd ..\..\..\..

cd %~dp0..
if exist "RAN_Intelligent_Controllers\Non-Real-Time-RIC\dep" rmdir /s /q "RAN_Intelligent_Controllers\Non-Real-Time-RIC\dep"
cd RAN_Intelligent_Controllers\Non-Real-Time-RIC
git clone https://gerrit.o-ran-sc.org/r/it/dep.git
cd dep
git checkout 5ad8cffbfe4b8aa5582fb9f6d1f8eb4be3376c70
git restore --source=HEAD :/
cd ..\..\..

cd %~dp0..
if exist "RAN_Intelligent_Controllers\Non-Real-Time-RIC\dep\ranpm" rmdir /s /q "RAN_Intelligent_Controllers\Non-Real-Time-RIC\dep\ranpm"
cd RAN_Intelligent_Controllers\Non-Real-Time-RIC\dep
git clone https://gerrit.o-ran-sc.org/r/nonrtric/plt/ranpm.git
cd ranpm
git checkout 5bc5869bbae98932cdb615226b0f683673368922
cd ..\..\..\..

cd %~dp0..
if exist "RAN_Intelligent_Controllers\Non-Real-Time-RIC\dep\ric-dep" rmdir /s /q "RAN_Intelligent_Controllers\Non-Real-Time-RIC\dep\ric-dep"
cd RAN_Intelligent_Controllers\Non-Real-Time-RIC\dep
git clone https://gerrit.o-ran-sc.org/r/ric-plt/ric-dep.git
cd ric-dep
git checkout 33b5940a15ea852d47f73521295eef53d295b7fd
cd ..\..\..\..

cd %~dp0..
if exist "RAN_Intelligent_Controllers\Non-Real-Time-RIC\dep\smo-install\multicloud-k8s" rmdir /s /q "RAN_Intelligent_Controllers\Non-Real-Time-RIC\dep\smo-install\multicloud-k8s"
cd RAN_Intelligent_Controllers\Non-Real-Time-RIC\dep\smo-install
git clone https://github.com/onap/multicloud-k8s.git
cd multicloud-k8s
git checkout 8bea0a13c223aff43f98f0cb6426379bb23e8894
cd ..\..\..\..\..

cd %~dp0..
if exist "RAN_Intelligent_Controllers\Non-Real-Time-RIC\dep\smo-install\onap_oom" rmdir /s /q "RAN_Intelligent_Controllers\Non-Real-Time-RIC\dep\smo-install\onap_oom"
cd RAN_Intelligent_Controllers\Non-Real-Time-RIC\dep\smo-install
git clone https://gerrit.onap.org/r/oom.git
cd onap_oom
git checkout ebe7cf54cecd93c9b11380f8deb93105da15fd21
cd ..\..\..\..\..

cd %~dp0..
if exist "RAN_Intelligent_Controllers\Non-Real-Time-RIC\nonrtric-controlpanel" rmdir /s /q "RAN_Intelligent_Controllers\Non-Real-Time-RIC\nonrtric-controlpanel"
cd RAN_Intelligent_Controllers\Non-Real-Time-RIC
git clone https://gerrit.o-ran-sc.org/r/portal/nonrtric-controlpanel.git
cd nonrtric-controlpanel
git checkout f337177ece41c036967ece8513e9f29b07deca34
cd ..\..\..

cd %~dp0..
if exist "RAN_Intelligent_Controllers\Non-Real-Time-RIC\rappmanager" rmdir /s /q "RAN_Intelligent_Controllers\Non-Real-Time-RIC\rappmanager"
cd RAN_Intelligent_Controllers\Non-Real-Time-RIC
git clone https://gerrit.o-ran-sc.org/r/nonrtric/plt/rappmanager.git
cd rappmanager
git checkout 688ab2c9ac9b1af06c30ddc28db9bcc5ecaaa096
cd ..\..\..

cd RAN_Intelligent_Controllers\Non-Real-Time-RIC
mkdir rApps
cd ..\..
cd %~dp0..
if exist "OpenAirInterface_Testbed\5G_Core_Network\open5gs" rmdir /s /q "OpenAirInterface_Testbed\5G_Core_Network\open5gs"
cd OpenAirInterface_Testbed\5G_Core_Network
git clone https://github.com/open5gs/open5gs.git
cd open5gs
git checkout 52ca325ed5b11104e2a4b77a1aacb7e44af01ab5
cd ..\..\..

cd %~dp0..
if exist "OpenAirInterface_Testbed\User_Equipment\openairinterface5g" rmdir /s /q "OpenAirInterface_Testbed\User_Equipment\openairinterface5g"
cd OpenAirInterface_Testbed\User_Equipment
git clone https://gitlab.eurecom.fr/oai/openairinterface5g.git
cd openairinterface5g
git checkout 627e60f5bdb0eefdfc79e6ccb69f653d87b310eb
cd ..\..\..

cd OpenAirInterface_Testbed\Next_Generation_Node_B
mklink /D openairinterface5g ..\User_Equipment\openairinterface5g
cd ..\..

cd %~dp0..
if exist "OpenAirInterface_Testbed\RAN_Intelligent_Controllers\Flexible-RIC\swig" rmdir /s /q "OpenAirInterface_Testbed\RAN_Intelligent_Controllers\Flexible-RIC\swig"
cd OpenAirInterface_Testbed\RAN_Intelligent_Controllers\Flexible-RIC
git clone https://github.com/swig/swig.git
cd swig
git checkout 935f9222a33008d606d997a90742b8a0e1bc31d9
cd ..\..\..\..

cd %~dp0..
if exist "OpenAirInterface_Testbed\RAN_Intelligent_Controllers\Flexible-RIC\flexric" rmdir /s /q "OpenAirInterface_Testbed\RAN_Intelligent_Controllers\Flexible-RIC\flexric"
cd OpenAirInterface_Testbed\RAN_Intelligent_Controllers\Flexible-RIC
git clone https://gitlab.eurecom.fr/mosaic5g/flexric.git
cd flexric
git checkout df754a85537f6db255b5330b8d83eda6a2742f25
cd ..\..\..\..


echo Repositories were cloned successfully.
pause
