REM NIST-developed software is provided by NIST as a public service. You may use,
REM copy, and distribute copies of the software in any medium, provided that you
REM keep intact this entire notice. You may improve, modify, and create derivative
REM works of the software or any portion of the software, and you may copy and
REM distribute such modifications or works. Modified works should carry a notice
REM stating that you changed the software and should note the date and nature of
REM any such change. Please explicitly acknowledge the National Institute of
REM Standards and Technology as the source of the software.
REM
REM NIST-developed software is expressly provided AS IS. NIST MAKES NO WARRANTY
REM OF ANY KIND, EXPRESS, IMPLIED, IN FACT, OR ARISING BY OPERATION OF LAW,
REM INCLUDING, WITHOUT LIMITATION, THE IMPLIED WARRANTY OF MERCHANTABILITY,
REM FITNESS FOR A PARTICULAR PURPOSE, NON-INFRINGEMENT, AND DATA ACCURACY. NIST
REM NEITHER REPRESENTS NOR WARRANTS THAT THE OPERATION OF THE SOFTWARE WILL BE
REM UNINTERRUPTED OR ERROR-FREE, OR THAT ANY DEFECTS WILL BE CORRECTED. NIST DOES
REM NOT WARRANT OR MAKE ANY REPRESENTATIONS REGARDING THE USE OF THE SOFTWARE OR
REM THE RESULTS THEREOF, INCLUDING BUT NOT LIMITED TO THE CORRECTNESS, ACCURACY,
REM RELIABILITY, OR USEFULNESS OF THE SOFTWARE.
REM
REM You are solely responsible for determining the appropriateness of using and
REM distributing the software and you assume all risks associated with its use,
REM including but not limited to the risks and costs of program errors, compliance
REM with applicable laws, damage to or loss of data, programs or equipment, and
REM the unavailability or interruption of operation. This software is not intended
REM to be used in any situation where a failure could cause risk of injury or
REM damage to property. The software developed by NIST employees is not subject to
REM copyright protection within the United States.

@echo off

REM This is an automatically generated script to download the testbed repositories to analyze the source code without requiring a full testbed build and installation.
REM WARNING: Please do not edit this file manually since it is overwritten with the script: ./Additional_Scripts/generate_download_dependency_repositories.bat.sh

echo Script: %~f0...

REM Change to the parent directory of the script
cd %~dp0..
if exist "5G_Core_Network\open5gs" rmdir /s /q "5G_Core_Network\open5gs"
cd "5G_Core_Network" >nul 2>&1
if not errorlevel 1 (
    git clone https://github.com/open5gs/open5gs.git
    cd "open5gs"
    git checkout 318eeb49a7dcdff733dec60e02d9c60aefca2fb9
    cd ..\..
) else (
    echo ERROR: Failed to cd to 5G_Core_Network. Skipping clone.
)

cd %~dp0..
if exist "5G_Core_Network/Additional_Cores_5GDeploy\5gdeploy" rmdir /s /q "5G_Core_Network/Additional_Cores_5GDeploy\5gdeploy"
cd "5G_Core_Network/Additional_Cores_5GDeploy" >nul 2>&1
if not errorlevel 1 (
    git clone https://github.com/usnistgov/5gdeploy.git
    cd ..
) else (
    echo ERROR: Failed to cd to 5G_Core_Network/Additional_Cores_5GDeploy. Skipping clone.
)

cd %~dp0..
if exist "User_Equipment\srsRAN_4G" rmdir /s /q "User_Equipment\srsRAN_4G"
cd "User_Equipment" >nul 2>&1
if not errorlevel 1 (
    git clone https://github.com/srsran/srsRAN_4G.git
    cd "srsRAN_4G"
    git checkout 6bcbd9e5bf8686aa7085202cd847c5ddd64a9c16
    cd ..\..
) else (
    echo ERROR: Failed to cd to User_Equipment. Skipping clone.
)

cd %~dp0..
if exist "User_Equipment\libzmq" rmdir /s /q "User_Equipment\libzmq"
cd "User_Equipment" >nul 2>&1
if not errorlevel 1 (
    git clone https://github.com/zeromq/libzmq.git
    cd "libzmq"
    git checkout 7d95ac02ae1af9a2f6896794d12b9de2ae30a3a8
    cd ..\..
) else (
    echo ERROR: Failed to cd to User_Equipment. Skipping clone.
)

cd %~dp0..
if exist "User_Equipment\czmq" rmdir /s /q "User_Equipment\czmq"
cd "User_Equipment" >nul 2>&1
if not errorlevel 1 (
    git clone https://github.com/zeromq/czmq.git
    cd "czmq"
    git checkout 6b435f533619a52d9e1c3fa43d5e40e50a046272
    cd ..\..
) else (
    echo ERROR: Failed to cd to User_Equipment. Skipping clone.
)

cd %~dp0..
if exist "Next_Generation_Node_B\ocudu" rmdir /s /q "Next_Generation_Node_B\ocudu"
cd "Next_Generation_Node_B" >nul 2>&1
if not errorlevel 1 (
    git clone https://gitlab.com/ocudu/ocudu.git
    cd "ocudu"
    git checkout 4d1fe417268ef19b5dd8677263f696602735eb85
    cd ..\..
) else (
    echo ERROR: Failed to cd to Next_Generation_Node_B. Skipping clone.
)

cd %~dp0..
if exist "Next_Generation_Node_B\ocudu_o1_adapter" rmdir /s /q "Next_Generation_Node_B\ocudu_o1_adapter"
cd "Next_Generation_Node_B" >nul 2>&1
if not errorlevel 1 (
    git clone https://gitlab.com/ocudu/ocudu_elements/ocudu_oran_apps/ocudu_o1_adapter.git
    cd "ocudu_o1_adapter"
    git checkout cbc03d78e9901c9a3df541194102529702d15991
    cd ..\..
) else (
    echo ERROR: Failed to cd to Next_Generation_Node_B. Skipping clone.
)

cd %~dp0..
if exist "Next_Generation_Node_B\ocudu_netconf" rmdir /s /q "Next_Generation_Node_B\ocudu_netconf"
cd "Next_Generation_Node_B" >nul 2>&1
if not errorlevel 1 (
    git clone https://gitlab.com/ocudu/ocudu_elements/ocudu_oran_apps/ocudu_netconf.git
    cd "ocudu_netconf"
    git checkout 6ed7cfbd031210fceeeb0d99f977dd3b85dfd183
    cd ..\..
) else (
    echo ERROR: Failed to cd to Next_Generation_Node_B. Skipping clone.
)

cd Next_Generation_Node_B
mklink /D libzmq ..\User_Equipment\libzmq
mklink /D czmq ..\User_Equipment\czmq
if not exist zmq_broker mkdir zmq_broker
cd zmq_broker
if not exist "multi_ue_scenario.grc" (
    curl -L --fail --silent --show-error -o multi_ue_scenario.grc https://gitlab.com/ocudu/ocudu_docs/-/raw/main/docs/user_manual/tutorials/srsue/assets/multi_ue_scenario.grc
    if errorlevel 1 (
        echo ERROR: Failed to download multi_ue_scenario.grc
        exit /b 1
    )
)
cd ..
cd ..\..

cd %~dp0..
if exist "RAN_Intelligent_Controllers\Near-Real-Time-RIC\ric-dep" rmdir /s /q "RAN_Intelligent_Controllers\Near-Real-Time-RIC\ric-dep"
cd "RAN_Intelligent_Controllers\Near-Real-Time-RIC" >nul 2>&1
if not errorlevel 1 (
    git clone https://gerrit.o-ran-sc.org/r/ric-plt/ric-dep.git
    cd "ric-dep"
    git checkout d9298b0865b69847c2ed0885f5077e703e5a6638
    cd ..\..\..
) else (
    echo ERROR: Failed to cd to RAN_Intelligent_Controllers\Near-Real-Time-RIC. Skipping clone.
)

cd %~dp0..
if exist "RAN_Intelligent_Controllers\Near-Real-Time-RIC\e2-interface" rmdir /s /q "RAN_Intelligent_Controllers\Near-Real-Time-RIC\e2-interface"
cd "RAN_Intelligent_Controllers\Near-Real-Time-RIC" >nul 2>&1
if not errorlevel 1 (
    git clone https://gerrit.o-ran-sc.org/r/sim/e2-interface.git
    cd "e2-interface"
    git checkout da6f82f286cdbb38af1178f82f85877b12c2f85b
    cd ..\..\..
) else (
    echo ERROR: Failed to cd to RAN_Intelligent_Controllers\Near-Real-Time-RIC. Skipping clone.
)

cd %~dp0..
if exist "RAN_Intelligent_Controllers\Near-Real-Time-RIC\appmgr" rmdir /s /q "RAN_Intelligent_Controllers\Near-Real-Time-RIC\appmgr"
cd "RAN_Intelligent_Controllers\Near-Real-Time-RIC" >nul 2>&1
if not errorlevel 1 (
    git clone https://gerrit.o-ran-sc.org/r/ric-plt/appmgr.git
    cd "appmgr"
    git checkout 2f70f24239e3f9281b899b7d5b4807cf36e062d1
    cd ..\..\..
) else (
    echo ERROR: Failed to cd to RAN_Intelligent_Controllers\Near-Real-Time-RIC. Skipping clone.
)

cd RAN_Intelligent_Controllers\Near-Real-Time-RIC
mkdir xApps
cd ..\..

cd %~dp0..
if exist "RAN_Intelligent_Controllers\Near-Real-Time-RIC\xApps\hw-go" rmdir /s /q "RAN_Intelligent_Controllers\Near-Real-Time-RIC\xApps\hw-go"
cd "RAN_Intelligent_Controllers\Near-Real-Time-RIC\xApps" >nul 2>&1
if not errorlevel 1 (
    git clone https://gerrit.o-ran-sc.org/r/ric-app/hw-go.git
    cd "hw-go"
    git checkout 3a0d348e429ea0f3f3d2a1d5eb54ec8758d1a262
    cd ..\..\..\..
) else (
    echo ERROR: Failed to cd to RAN_Intelligent_Controllers\Near-Real-Time-RIC\xApps. Skipping clone.
)

cd %~dp0..
if exist "RAN_Intelligent_Controllers\Near-Real-Time-RIC\xApps\hw-python" rmdir /s /q "RAN_Intelligent_Controllers\Near-Real-Time-RIC\xApps\hw-python"
cd "RAN_Intelligent_Controllers\Near-Real-Time-RIC\xApps" >nul 2>&1
if not errorlevel 1 (
    git clone https://gerrit.o-ran-sc.org/r/ric-app/hw-python.git
    cd ..\..\..
) else (
    echo ERROR: Failed to cd to RAN_Intelligent_Controllers\Near-Real-Time-RIC\xApps. Skipping clone.
)

cd %~dp0..
if exist "RAN_Intelligent_Controllers\Near-Real-Time-RIC\xApps\hw-rust" rmdir /s /q "RAN_Intelligent_Controllers\Near-Real-Time-RIC\xApps\hw-rust"
cd "RAN_Intelligent_Controllers\Near-Real-Time-RIC\xApps" >nul 2>&1
if not errorlevel 1 (
    git clone https://gerrit.o-ran-sc.org/r/ric-app/hw-rust.git
    cd ..\..\..
) else (
    echo ERROR: Failed to cd to RAN_Intelligent_Controllers\Near-Real-Time-RIC\xApps. Skipping clone.
)

cd %~dp0..
if exist "RAN_Intelligent_Controllers\Near-Real-Time-RIC\xApps\kpimon-go" rmdir /s /q "RAN_Intelligent_Controllers\Near-Real-Time-RIC\xApps\kpimon-go"
cd "RAN_Intelligent_Controllers\Near-Real-Time-RIC\xApps" >nul 2>&1
if not errorlevel 1 (
    git clone https://gerrit.o-ran-sc.org/r/ric-app/kpimon-go.git
    cd "kpimon-go"
    git checkout 8bbbbbb90093db01f88820de755bce0ee2189c88
    cd ..\..\..\..
) else (
    echo ERROR: Failed to cd to RAN_Intelligent_Controllers\Near-Real-Time-RIC\xApps. Skipping clone.
)

cd %~dp0..
if exist "RAN_Intelligent_Controllers\Near-Real-Time-RIC\xApps\ad-cell" rmdir /s /q "RAN_Intelligent_Controllers\Near-Real-Time-RIC\xApps\ad-cell"
cd "RAN_Intelligent_Controllers\Near-Real-Time-RIC\xApps" >nul 2>&1
if not errorlevel 1 (
    git clone https://gerrit.o-ran-sc.org/r/ric-app/ad-cell.git
    cd "ad-cell"
    git checkout f1338a030f6c2c5a6ab2a970c0fe964c92aafa8f
    cd ..\..\..\..
) else (
    echo ERROR: Failed to cd to RAN_Intelligent_Controllers\Near-Real-Time-RIC\xApps. Skipping clone.
)

cd %~dp0..
if exist "RAN_Intelligent_Controllers\Near-Real-Time-RIC\xApps\ad" rmdir /s /q "RAN_Intelligent_Controllers\Near-Real-Time-RIC\xApps\ad"
cd "RAN_Intelligent_Controllers\Near-Real-Time-RIC\xApps" >nul 2>&1
if not errorlevel 1 (
    git clone https://gerrit.o-ran-sc.org/r/ric-app/ad.git
    cd "ad"
    git checkout f9f97b8c682d890395e3de5a56450ebb04a5630b
    cd ..\..\..\..
) else (
    echo ERROR: Failed to cd to RAN_Intelligent_Controllers\Near-Real-Time-RIC\xApps. Skipping clone.
)

cd %~dp0..
if exist "RAN_Intelligent_Controllers\Near-Real-Time-RIC\xApps\qp" rmdir /s /q "RAN_Intelligent_Controllers\Near-Real-Time-RIC\xApps\qp"
cd "RAN_Intelligent_Controllers\Near-Real-Time-RIC\xApps" >nul 2>&1
if not errorlevel 1 (
    git clone https://gerrit.o-ran-sc.org/r/ric-app/qp.git
    cd "qp"
    git checkout 47a35cafc3f90aed8b6fa711c37b131f06061ca6
    cd ..\..\..\..
) else (
    echo ERROR: Failed to cd to RAN_Intelligent_Controllers\Near-Real-Time-RIC\xApps. Skipping clone.
)

cd %~dp0..
if exist "RAN_Intelligent_Controllers\Near-Real-Time-RIC\xApps\rc" rmdir /s /q "RAN_Intelligent_Controllers\Near-Real-Time-RIC\xApps\rc"
cd "RAN_Intelligent_Controllers\Near-Real-Time-RIC\xApps" >nul 2>&1
if not errorlevel 1 (
    git clone https://gerrit.o-ran-sc.org/r/ric-app/rc.git
    cd "rc"
    git checkout a2282eedc9e32f60298bf530456ad367bef0824b
    cd ..\..\..\..
) else (
    echo ERROR: Failed to cd to RAN_Intelligent_Controllers\Near-Real-Time-RIC\xApps. Skipping clone.
)

cd %~dp0..
if exist "RAN_Intelligent_Controllers\Near-Real-Time-RIC\xApps\ts" rmdir /s /q "RAN_Intelligent_Controllers\Near-Real-Time-RIC\xApps\ts"
cd "RAN_Intelligent_Controllers\Near-Real-Time-RIC\xApps" >nul 2>&1
if not errorlevel 1 (
    git clone https://gerrit.o-ran-sc.org/r/ric-app/ts.git
    cd "ts"
    git checkout 19e169b2e81a0dbaf3d9dc526de0415cc995ee8b
    cd ..\..\..\..
) else (
    echo ERROR: Failed to cd to RAN_Intelligent_Controllers\Near-Real-Time-RIC\xApps. Skipping clone.
)

cd %~dp0..
if exist "RAN_Intelligent_Controllers\Non-Real-Time-RIC\dep" rmdir /s /q "RAN_Intelligent_Controllers\Non-Real-Time-RIC\dep"
cd "RAN_Intelligent_Controllers\Non-Real-Time-RIC" >nul 2>&1
if not errorlevel 1 (
    git clone https://gerrit.o-ran-sc.org/r/it/dep.git
    cd "dep"
    git checkout 1daedf545ec1b5f6d4a7740c49ea44d80459f24c
    git restore --source=HEAD :/
    cd ..\..\..
) else (
    echo ERROR: Failed to cd to RAN_Intelligent_Controllers\Non-Real-Time-RIC. Skipping clone.
)

cd %~dp0..
if exist "RAN_Intelligent_Controllers\Non-Real-Time-RIC\rappmanager" rmdir /s /q "RAN_Intelligent_Controllers\Non-Real-Time-RIC\rappmanager"
cd "RAN_Intelligent_Controllers\Non-Real-Time-RIC" >nul 2>&1
if not errorlevel 1 (
    git clone https://gerrit.o-ran-sc.org/r/nonrtric/plt/rappmanager.git
    cd "rappmanager"
    git checkout 3b4813b6dab278581601a06185c146ea47b4ebb7
    cd ..\..\..
) else (
    echo ERROR: Failed to cd to RAN_Intelligent_Controllers\Non-Real-Time-RIC. Skipping clone.
)

cd %~dp0..
if exist "RAN_Intelligent_Controllers\Non-Real-Time-RIC\dep\ranpm" rmdir /s /q "RAN_Intelligent_Controllers\Non-Real-Time-RIC\dep\ranpm"
cd "RAN_Intelligent_Controllers\Non-Real-Time-RIC\dep" >nul 2>&1
if not errorlevel 1 (
    git clone https://gerrit.o-ran-sc.org/r/nonrtric/plt/ranpm.git
    cd "ranpm"
    git checkout f0ef45cb96961334b9525c546534b822f055e24c
    cd ..\..\..\..
) else (
    echo ERROR: Failed to cd to RAN_Intelligent_Controllers\Non-Real-Time-RIC\dep. Skipping clone.
)

cd %~dp0..
if exist "RAN_Intelligent_Controllers\Non-Real-Time-RIC\dep\ric-dep" rmdir /s /q "RAN_Intelligent_Controllers\Non-Real-Time-RIC\dep\ric-dep"
cd "RAN_Intelligent_Controllers\Non-Real-Time-RIC\dep" >nul 2>&1
if not errorlevel 1 (
    git clone https://gerrit.o-ran-sc.org/r/ric-plt/ric-dep.git
    cd "ric-dep"
    git checkout d9298b0865b69847c2ed0885f5077e703e5a6638
    cd ..\..\..\..
) else (
    echo ERROR: Failed to cd to RAN_Intelligent_Controllers\Non-Real-Time-RIC\dep. Skipping clone.
)

cd %~dp0..
if exist "RAN_Intelligent_Controllers\Non-Real-Time-RIC\dep\smo-install\multicloud-k8s" rmdir /s /q "RAN_Intelligent_Controllers\Non-Real-Time-RIC\dep\smo-install\multicloud-k8s"
cd "RAN_Intelligent_Controllers\Non-Real-Time-RIC\dep\smo-install" >nul 2>&1
if not errorlevel 1 (
    git clone https://github.com/onap/multicloud-k8s.git
    cd "multicloud-k8s"
    git checkout a3c6f080e9a015c7aab0d351af3864f239fb2931
    cd ..\..\..\..\..
) else (
    echo ERROR: Failed to cd to RAN_Intelligent_Controllers\Non-Real-Time-RIC\dep\smo-install. Skipping clone.
)

cd %~dp0..
if exist "RAN_Intelligent_Controllers\Non-Real-Time-RIC\dep\smo-install\onap_oom" rmdir /s /q "RAN_Intelligent_Controllers\Non-Real-Time-RIC\dep\smo-install\onap_oom"
cd "RAN_Intelligent_Controllers\Non-Real-Time-RIC\dep\smo-install" >nul 2>&1
if not errorlevel 1 (
    git clone https://gerrit.onap.org/r/oom.git
    cd "onap_oom"
    git checkout 2214f66e9d9f757239d0297353d9194f782e9eac
    cd ..\..\..\..\..
) else (
    echo ERROR: Failed to cd to RAN_Intelligent_Controllers\Non-Real-Time-RIC\dep\smo-install. Skipping clone.
)

cd %~dp0..
if exist "RAN_Intelligent_Controllers\Non-Real-Time-RIC\nonrtric-controlpanel" rmdir /s /q "RAN_Intelligent_Controllers\Non-Real-Time-RIC\nonrtric-controlpanel"
cd "RAN_Intelligent_Controllers\Non-Real-Time-RIC" >nul 2>&1
if not errorlevel 1 (
    git clone https://gerrit.o-ran-sc.org/r/portal/nonrtric-controlpanel.git
    cd "nonrtric-controlpanel"
    git checkout 9f0bc855a687f918548d5dcea7a43913256cdd54
    cd ..\..\..
) else (
    echo ERROR: Failed to cd to RAN_Intelligent_Controllers\Non-Real-Time-RIC. Skipping clone.
)

cd RAN_Intelligent_Controllers\Non-Real-Time-RIC
mkdir rApps
cd ..\..

cd %~dp0..
if not exist "OpenAirInterface_Testbed\5G_Core_Network\open5gs" (
    cd "OpenAirInterface_Testbed\5G_Core_Network" >nul 2>&1
    if not errorlevel 1 (
        git clone https://github.com/open5gs/open5gs.git
        cd "open5gs"
        git checkout 318eeb49a7dcdff733dec60e02d9c60aefca2fb9
        cd ..\..\..
    ) else (
        echo ERROR: Failed to cd to OpenAirInterface_Testbed\5G_Core_Network. Skipping clone.
    )
)

cd %~dp0..
if exist "OpenAirInterface_Testbed\5G_Core_Network\Additional_Cores_5GDeploy\5gdeploy" rmdir /s /q "OpenAirInterface_Testbed\5G_Core_Network\Additional_Cores_5GDeploy\5gdeploy"
cd "OpenAirInterface_Testbed\5G_Core_Network\Additional_Cores_5GDeploy" >nul 2>&1
if not errorlevel 1 (
    git clone https://github.com/usnistgov/5gdeploy.git
    cd ..\..\..
) else (
    echo ERROR: Failed to cd to OpenAirInterface_Testbed\5G_Core_Network\Additional_Cores_5GDeploy. Skipping clone.
)

cd %~dp0..
if exist "OpenAirInterface_Testbed\User_Equipment\openairinterface5g" rmdir /s /q "OpenAirInterface_Testbed\User_Equipment\openairinterface5g"
cd "OpenAirInterface_Testbed\User_Equipment" >nul 2>&1
if not errorlevel 1 (
    git clone https://gitlab.eurecom.fr/oai/openairinterface5g.git
    cd "openairinterface5g"
    git checkout af4b0d53e9f4c3bf0e5f82f58781eac07f312b86
    cd ..\..\..
) else (
    echo ERROR: Failed to cd to OpenAirInterface_Testbed\User_Equipment. Skipping clone.
)

cd OpenAirInterface_Testbed\Next_Generation_Node_B
mklink /D openairinterface5g ..\User_Equipment\openairinterface5g
cd ..\..

cd %~dp0..
if exist "OpenAirInterface_Testbed\Next_Generation_Node_B\o1-adapter" rmdir /s /q "OpenAirInterface_Testbed\Next_Generation_Node_B\o1-adapter"
cd "OpenAirInterface_Testbed\Next_Generation_Node_B" >nul 2>&1
if not errorlevel 1 (
    git clone https://gitlab.eurecom.fr/oai/o1-adapter.git
    cd "o1-adapter"
    git checkout 1cd696960d9b3d28461caa61ced4b173eff1eec9
    cd ..\..\..
) else (
    echo ERROR: Failed to cd to OpenAirInterface_Testbed\Next_Generation_Node_B. Skipping clone.
)

cd %~dp0..
if exist "OpenAirInterface_Testbed\RAN_Intelligent_Controllers\Flexible-RIC\swig" rmdir /s /q "OpenAirInterface_Testbed\RAN_Intelligent_Controllers\Flexible-RIC\swig"
cd "OpenAirInterface_Testbed\RAN_Intelligent_Controllers\Flexible-RIC" >nul 2>&1
if not errorlevel 1 (
    git clone https://github.com/swig/swig.git
    cd "swig"
    git checkout b8f7a107cbd81058f8c5818bbad48d78903f6c14
    cd ..\..\..\..
) else (
    echo ERROR: Failed to cd to OpenAirInterface_Testbed\RAN_Intelligent_Controllers\Flexible-RIC. Skipping clone.
)

cd %~dp0..
if exist "OpenAirInterface_Testbed\RAN_Intelligent_Controllers\Flexible-RIC\flexric" rmdir /s /q "OpenAirInterface_Testbed\RAN_Intelligent_Controllers\Flexible-RIC\flexric"
cd "OpenAirInterface_Testbed\RAN_Intelligent_Controllers\Flexible-RIC" >nul 2>&1
if not errorlevel 1 (
    git clone https://gitlab.eurecom.fr/mosaic5g/flexric.git
    cd "flexric"
    git checkout e5e5873f36911c14095a6733275d16464f74d3bf
    cd ..\..\..\..
) else (
    echo ERROR: Failed to cd to OpenAirInterface_Testbed\RAN_Intelligent_Controllers\Flexible-RIC. Skipping clone.
)


echo Repositories were cloned successfully.
pause
