# /*
# * Licensed to the OpenAirInterface (OAI) Software Alliance under one or more
# * contributor license agreements.  See the NOTICE file distributed with
# * this work for additional information regarding copyright ownership.
# * The OpenAirInterface Software Alliance licenses this file to You under
# * the OAI Public License, Version 1.1  (the "License"); you may not use this file
# * except in compliance with the License.
# * You may obtain a copy of the License at
# *
# *      http://www.openairinterface.org/?page_id=698
# *
# * Copyright: Fraunhofer Heinrich Hertz Institute
# *
# * Unless required by applicable law or agreed to in writing, software
# * distributed under the License is distributed on an "AS IS" BASIS,
# * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# * See the License for the specific language governing permissions and
# * limitations under the License.
# *-------------------------------------------------------------------------------
# * For more information about the OpenAirInterface (OAI) Software Alliance:
# *      contact@openairinterface.org
# */

FROM ubuntu:22.04 as builder
LABEL maintainer="adrian.lita@highstreet-technologies.com"

RUN apt-get update && DEBIAN_FRONTEND="noninteractive" apt-get install -y \
    # basic tools
    tzdata build-essential git cmake pkg-config unzip wget \
    # libyang dependencies
    libpcre2-dev \
    # libssh dependencies
    zlib1g-dev libssl-dev \
    # libtelnet dependencies
    autoconf libtool \
    && rm -rf /var/lib/apt/lists/*

# add netconf user and configure access
RUN \
    adduser --system netconf && \
    echo "netconf:netconf!" | chpasswd

### FTP and SFTP configuration
RUN \
    mkdir /ftp && \
    chown -R netconf /ftp && \
    mkdir /var/run/vsftpd && \
    mkdir /var/run/vsftpd/empty  && \
    mkdir /run/sshd && \
    echo "Match User netconf\n    ChrootDirectory /\n    X11Forwarding no\n    AllowTcpForwarding no\n    ForceCommand internal-sftp -d /ftp" >> /etc/ssh/sshd_config

COPY ./docker/config/vsftpd.conf /etc/vsftpd.conf
COPY ./docker/config/vsftpd.userlist /etc/vsftpd.userlist

RUN \
    mkdir -p /adapter/scripts

# run dependencies install for netconf
COPY ./docker/scripts/netconf_dep_install.sh /adapter/scripts/netconf_dep_install.sh
RUN \
    /adapter/scripts/netconf_dep_install.sh

# Initialize netopeer2
RUN \
    /usr/local/share/netopeer2/merge_hostkey.sh && \
    /usr/local/share/netopeer2/merge_config.sh

# get and install required YANG libraries
COPY ./docker/scripts/get-yangs.sh /adapter/scripts/get-yangs.sh
COPY ./docker/scripts/install-yangs.sh /adapter/scripts/install-yangs.sh
RUN \
    cd /adapter/scripts && \
    mkdir yang && \
    ./get-yangs.sh && \
    ./install-yangs.sh

COPY ./src /adapter/src
RUN \
    cd /adapter/src && \
    ./build.sh



FROM ubuntu:22.04 as adapter-gnb
LABEL maintainer="adrian.lita@highstreet-technologies.com"

# init ubuntu
RUN apt-get update -y && apt-get upgrade -y

# install tools
RUN apt-get update && apt-get install -y --no-install-recommends \
    psmisc \
    unzip \
    wget \
    openssl \
    openssh-client \
    vsftpd \
    openssh-server \
    && rm -rf /var/lib/apt/lists/*

# add netconf user and configure access
RUN \
    adduser --system netconf && \
    echo "netconf:netconf!" | chpasswd && \
    mkdir -p /home/netconf/.ssh

COPY --from=builder /usr/local/bin /usr/local/bin
COPY --from=builder /usr/local/lib /usr/local/lib
COPY --from=builder /usr/local/sbin /usr/local/sbin
COPY --from=builder /usr/local/share /usr/local/share

COPY --from=builder /etc/sysrepo /etc/sysrepo
RUN ldconfig

# # copy SSH related scripts and keys
# COPY --from=builder /home/netconf/.ssh /home/netconf/.ssh

## FTP and SFTP configuration
RUN \
    mkdir /ftp && \
    chown -R netconf /ftp && \
    mkdir /var/run/vsftpd && \
    mkdir /var/run/vsftpd/empty  && \
    mkdir /run/sshd && \
    echo "Match User netconf\n    ChrootDirectory /\n    X11Forwarding no\n    AllowTcpForwarding no\n    ForceCommand internal-sftp -d /ftp" >> /etc/ssh/sshd_config
COPY --from=builder /etc/vsftpd.conf /etc/vsftpd.conf
COPY --from=builder /etc/vsftpd.userlist /etc/vsftpd.userlist

RUN \
    mkdir -p /adapter/config

COPY --from=builder /adapter/src/gnb-adapter /adapter/gnb-adapter

COPY ./docker/config/config.json /adapter/config/config.json
COPY ./docker/config/ves-new-alarm.json /adapter/config/ves-new-alarm.json
COPY ./docker/config/ves-clear-alarm.json /adapter/config/ves-clear-alarm.json
COPY ./docker/config/ves-file-ready.json /adapter/config/ves-file-ready.json
COPY ./docker/config/ves-pnf-registration.json /adapter/config/ves-pnf-registration.json
COPY ./docker/config/ves-heartbeat.json /adapter/config/ves-heartbeat.json
COPY ./docker/config/pmData-measData.xml /adapter/config/pmData-measData.xml

COPY ./docker/scripts/adapter_entrypoint.sh /adapter

WORKDIR /adapter
ENTRYPOINT [ "/adapter/adapter_entrypoint.sh" ]
