apiVersion: apps/v1
kind: Deployment
metadata:
  name: open5gs-amf
  namespace: corbin-oran
  labels:
    app: open5gs-amf
    component: open5gs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: open5gs-amf
  template:
    metadata:
      labels:
        app: open5gs-amf
        component: open5gs
    spec:
      containers:
      - name: amf
        image: open5gs/open5gs:v2.7.0
        command: ["/usr/bin/open5gs-amfd", "-c", "/etc/open5gs/amf.yaml"]
        ports:
        - containerPort: 38412
          protocol: SCTP
        - containerPort: 7777
          protocol: TCP
        env:
        - name: DB_URI
          value: mongodb://mongodb-service:27017/open5gs
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        volumeMounts:
        - name: amf-config
          mountPath: /etc/open5gs/amf.yaml
          subPath: amf.yaml
      volumes:
      - name: amf-config
        configMap:
          name: open5gs-amf-config
---
apiVersion: v1
kind: Service
metadata:
  name: open5gs-amf-service
  namespace: corbin-oran
  labels:
    app: open5gs-amf
spec:
  selector:
    app: open5gs-amf
  ports:
  - name: ngap
    port: 38412
    targetPort: 38412
    protocol: SCTP
  - name: sbi
    port: 7777
    targetPort: 7777
    protocol: TCP
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: open5gs-amf-config
  namespace: corbin-oran
data:
  amf.yaml: |
    amf:
      sbi:
        - addr: 0.0.0.0
          port: 7777
      ngap:
        - addr: 0.0.0.0
          port: 38412
      metrics:
        - addr: 0.0.0.0
          port: 9090
      guami:
        - plmn_id:
            mcc: 001
            mnc: 01
          amf_id:
            region: 2
            set: 1
      tai:
        - plmn_id:
            mcc: 001
            mnc: 01
          tac: 1
      plmn_support:
        - plmn_id:
            mcc: 001
            mnc: 01
          s_nssai:
            - sst: 1
      security:
        integrity_order: [ NIA2, NIA1, NIA0 ]
        ciphering_order: [ NEA0, NEA1, NEA2 ]
      network_name:
        full: Open5GS
      amf_name: open5gs-amf
