apiVersion: v1
kind: ConfigMap
metadata:
  name: open5gs-smf-config
  namespace: corbin-oran
data:
  smf.yaml: |
    logger:
      level: info
    
    global:
      max:
        ue: 1024
    
    smf:
      sbi:
        server:
          - address: 0.0.0.0
            port: 7777
        client:
          scp:
            - uri: http://open5gs-nrf-service:7777
      pfcp:
        server:
          - address: 0.0.0.0
            port: 8805
        client:
          upf:
            - address: open5gs-upf-service
      gtpc:
        server:
          - address: 0.0.0.0
            port: 2123
      gtpu:
        server:
          - address: 0.0.0.0
            port: 2152
      session:
        - subnet: 10.45.0.0/16
          gateway: 10.45.0.1
        - subnet: 2001:db8:cafe::/48
          gateway: 2001:db8:cafe::1
      dns:
        - 8.8.8.8
        - 8.8.4.4
        - 2001:4860:4860::8888
        - 2001:4860:4860::8844
      mtu: 1400
      
    info:
      - s_nssai:
          - sst: 1
            dnn:
              - internet
        tai:
          - plmn_id:
              mcc: 001
              mnc: 01
            tac: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: open5gs-smf
  namespace: corbin-oran
  labels:
    app: open5gs-smf
    component: open5gs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: open5gs-smf
  template:
    metadata:
      labels:
        app: open5gs-smf
        component: open5gs
    spec:
      containers:
      - name: smf
        image: openverso/open5gs:latest
        command: ["open5gs-smfd"]
        args: ["-c", "/open5gs/config/smf.yaml"]
        ports:
        - containerPort: 7777
          protocol: TCP
          name: sbi
        - containerPort: 8805
          protocol: UDP
          name: pfcp
        - containerPort: 2123
          protocol: UDP
          name: gtpc
        - containerPort: 2152
          protocol: UDP
          name: gtpu
        env:
        - name: DB_URI
          value: mongodb://mongodb-service:27017/open5gs
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "300m"
        volumeMounts:
        - name: smf-config
          mountPath: /open5gs/config/smf.yaml
          subPath: smf.yaml
        livenessProbe:
          httpGet:
            path: /
            port: 7777
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 7777
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: smf-config
        configMap:
          name: open5gs-smf-config
