USER-SUPPLIED VALUES:
cds:
  enabled: false
config:
  sdnr:
    enabled: true
    kafka:
      enabled: true
    mariadb:
      enabled: true
    mode: dm
    mountpointRegistrarEnabled: true
    mountpointStateProviderEnabled: true
    netconfCallHome:
      enabled: true
    sdnrdbTrustAllCerts: true
    sdnronly: false
dgbuilder:
  enabled: false
elasticsearch:
  enabled: false
enabled: true
global:
  aafEnabled: false
  addTestingComponents: true
  authorizationPolicies:
    enabled: false
  busyboxImage: busybox:1.37.0
  centralizedLoggingEnabled: false
  certificate:
    default:
      duration: 8760h
      issuer:
        group: certmanager.onap.org
        kind: CMPv2Issuer
        name: cmpv2-issuer-onap
      renewBefore: 720h
      subject:
        country: US
        locality: San-Francisco
        organization: Linux-Foundation
        organizationalUnit: ONAP
        province: California
  clusterName: cluster.local
  cmpv2Enabled: false
  createDefaultRoles: false
  curlImage: curlimages/curl:8.14.1
  debugEnabled: false
  dockerHubRepository: nexus3.onap.org:10001
  elasticRepository: docker.elastic.co
  envsubstImage: dibi/envsubst:latest
  flavor: unlimited
  githubContainerRegistry: ghcr.io
  googleK8sRepository: k8s.gcr.io
  htpasswdImage: xmartlabs/htpasswd:latest
  imagePullSecrets:
  - '{{ include "common.namespace" . }}-docker-registry-key'
  imageRegistry: nexus3.onap.org:10001
  ingress:
    commonGateway:
      httpListener: ""
      httpsListener: ""
      name: ""
    config:
      ssl: redirect
    enable_all: false
    enabled: false
    ingressClass: null
    ingressSelector: ingress
    namespace: istio-ingress
    provider: istio
    virtualhost:
      baseurl: simpledemo.onap.org
      postaddr: ""
      preaddr: ""
  jreImage: onap/integration-java11:10.0.0
  kubectlImage: bitnami/kubectl:1.22.16
  loggingImage: beats/filebeat:5.5.0
  loggingRepository: docker.elastic.co
  mariadbContainerRegistry: docker-registry3.mariadb.com
  mariadbGalera:
    enableServiceAccount: false
    useOperator: true
  mariadbImage: mariadb:11.7.2
  masterPassword: secretpassword
  metrics:
    custom_resources: false
    enabled: true
  mongodbImage: percona/percona-server-mongodb:7.0.16-10
  msbEnabled: true
  nginxImage: bitnami/nginx:1.29.0
  nodePortPrefix: 302
  nodePortPrefixExt: 304
  offlineDeploymentBuild: false
  passwordStrength: long
  persistence:
    enableDefaultStorageclass: false
    mountPath: /dockerdata-nfs
    parameters: {}
    storageClass: smo-storage
    storageclassProvisioner: kubernetes.io/no-provisioner
    volumeReclaimPolicy: Retain
  platform:
    certificates:
      clientSecretName: oom-cert-service-client-tls-secret
      keystoreKeyRef: keystore.jks
      keystorePasswordSecretKey: password
      keystorePasswordSecretName: oom-cert-service-certificates-password
      truststoreKeyRef: truststore.jks
      truststorePasswordSecretKey: password
      truststorePasswordSecretName: oom-cert-service-certificates-password
  postgresImage: crunchydata/crunchy-postgres:centos8-13.2-4.6.1
  prometheusEnabled: false
  pullPolicy: IfNotPresent
  quayRepository: quay.io
  readinessImage: onap/oom/readiness:6.2.0
  readinessRepository: oomk8s
  repository: nexus3.onap.org:10001
  repositoryCred:
    password: docker
    user: docker
  serviceMesh:
    enabled: false
    engine: istio
    nativeSidecars: false
    tls: true
  tlsEnabled: false
  tracing:
    collector:
      baseUrl: http://jaeger-collector.istio-config
      port:
        grpc: 14250
        otlpGrpc: 4317
        zipkin: 9411
    enabled: false
    sampling:
      probability: 1
image: onap/sdnc-image:2.6.1
mysql:
  replicaCount: 1
network-name-gen:
  enabled: false
replicaCount: 1
sdnc-ansible-server:
  enabled: true
  image: onap/sdnc-ansible-server-image:2.6.1
sdnc-web:
  image: onap/sdnc-web-image:2.6.1
ueb-listener:
  enabled: false
  image: onap/sdnc-ueb-listener-image:2.6.1
