variables:
  GIT_DEPTH: "1"
  GIT_STRATEGY: none #fetch
  GIT_SUBMODULE_STRATEGY: none
  GIT_CONFIG_COUNT: "1"
  GIT_CONFIG_KEY_0: "safe.directory"
  GIT_CONFIG_VALUE_0: "*"
  GIT_SSL_NO_VERIFY: "1"
  DEBIAN_FRONTEND: noninteractive
  FF_USE_FASTZIP: true
  ARTIFACT_COMPRESSION_LEVEL: "slowest"
  CACHE_COMPRESSION_LEVEL: "slowest"
  WORKSPACE_CACHE_KEY: "testbed-workspace:${CI_PIPELINE_ID}"


default:
  tags: [testbed-ci-runner]
  cache:
    key: "$WORKSPACE_CACHE_KEY"
    policy: pull-push
    when: always
    untracked: true
  # artifacts:
  #   paths:
  #     - ./
  #   expire_in: 1 day
  #   when: always
  before_script:
    - echo 'debconf debconf/frontend select Noninteractive' | sudo debconf-set-selections
    - export DEBIAN_FRONTEND=noninteractive
    - cd "$CI_PROJECT_DIR"
    - pwd
    - tree . -d
  after_script:
    - sudo chown --recursive "$USER" "$CI_PROJECT_DIR" || true

stages:
  - initialization
  - install_testbed_1
  - install_testbed_2
  - uninstall_testbed_1
  - uninstall_testbed_2

################################################################################
############################### INITIALIZATION #################################
################################################################################

uninstall_all_components:
  stage: initialization
  interruptible: true
  resource_group: testbed
  variables:
    GIT_STRATEGY: none
  allow_failure: true
  script:
    - |
      if [[ -f "5G_Core_Network/options.yaml" && -f "full_uninstall.sh" && -f "OpenAirInterface_Testbed/full_uninstall.sh" ]]; then
        # Testbed 1
        sed -i -E 's/^core_to_use:.*/core_to_use: open5gs/' 5G_Core_Network/options.yaml
        ./full_uninstall.sh
        # Testbed 2
        sed -i -E 's/^core_to_use:.*/core_to_use: 5gdeploy-oai/' 5G_Core_Network/options.yaml
        cd OpenAirInterface_Testbed
        ./full_uninstall.sh
        cd ..
        sed -i -E 's/^core_to_use:.*/core_to_use: open5gs/' 5G_Core_Network/options.yaml
      else
        echo "Repositories don't exist yet for uninstall_all_components, skipping."
      fi
  retry: 2

workspace_preclean:
  stage: initialization
  interruptible: true
  resource_group: testbed
  needs: [uninstall_all_components]
  variables:
    GIT_STRATEGY: none
  script:
    - sudo rm -rf * && sudo rm -rf .git*
  cache:
    key: "$WORKSPACE_CACHE_KEY"
    policy: pull
    when: always
    untracked: true

clone_and_install_dependencies:
  stage: initialization
  interruptible: true
  resource_group: testbed
  needs: [workspace_preclean]
  variables:
    GIT_STRATEGY: clone
  script:

    - sudo rm -f /var/lib/dpkg/lock-frontend /var/lib/dpkg/lock || true
    - sudo dpkg --configure -a || true
    - |
      if dpkg -s mongosh >/dev/null 2>&1 || ls /var/lib/dpkg/info/mongosh* >/dev/null 2>&1; then
        echo "Purging broken mongosh package..."
        sudo dpkg --remove --force-remove-reinstreq mongosh || true
        sudo dpkg --purge mongosh || true
        sudo rm -f /var/lib/dpkg/info/mongosh.* || true
      fi
    - sudo apt-get -y -f install || true
    - sudo apt-get update
    - sudo apt-get install -y sudo bash grep coreutils curl wget git gnupg lsb-release tree
    - sudo apt-get install -y --no-install-recommends tzdata
    - sudo update-ca-certificates || true
  cache:
    key: "$WORKSPACE_CACHE_KEY"
    policy: push
    when: always
    untracked: true
  retry: 2

# ################################################################################
# ########################### KUBERNETES_TESTING_ONLY ############################
# ################################################################################
# install_just_oran_sc_nearrtric:
#   stage: just-test-kubernetes
#   interruptible: true
#   resource_group: testbed
#   script:
#     - cd RAN_Intelligent_Controllers/Near-Real-Time-RIC
#     - ./full_install.sh
#     - cd ..
#   artifacts:
#     expire_in: 1 day
#     when: always
#     # paths:
#     #   - ./
#   retry: 2

################################################################################
########################### TESTBED 1 INSTALLATION #############################
################################################################################

install_open5gs:
  stage: install_testbed_1
  interruptible: true
  resource_group: testbed
  needs: [clone_and_install_dependencies]
  script:
    - cd OpenAirInterface_Testbed/5G_Core_Network
    - "sed -i -E 's/^core_to_use:.*/core_to_use: open5gs/' options.yaml"
    - ./full_install.sh
    - cd ../..
  retry: 2

install_oai_ue_gnb:
  stage: install_testbed_1
  interruptible: true
  resource_group: testbed
  needs: [install_open5gs]
  script:
    - cd OpenAirInterface_Testbed/User_Equipment
    - ./full_install.sh
    - cd ../..
    - cd OpenAirInterface_Testbed/Next_Generation_Node_B
    - ./full_install.sh
    - cd ../..
  retry: 2

install_flexric:
  stage: install_testbed_1
  interruptible: true
  resource_group: testbed
  needs: [install_oai_ue_gnb]
  script:
    - cd OpenAirInterface_Testbed/RAN_Intelligent_Controllers/Flexible-RIC
    - ./full_install.sh
    - cd ../../..
  retry: 2

configure_oai_testbed:
  stage: install_testbed_1
  interruptible: true
  resource_group: testbed
  needs: [install_flexric]
  script:
    - cd OpenAirInterface_Testbed
    - ./generate_configurations.sh
    - cd ..
  retry: 2

############################ TODO: END-TO-END TESTS ############################


################################################################################
########################### TESTBED 2 INSTALLATION #############################
################################################################################

install_srsran_ue:
  stage: install_testbed_2
  interruptible: true
  resource_group: testbed
  needs: [configure_oai_testbed]
  script:
    - cd User_Equipment
    - ./full_install.sh
    - cd ..
  retry: 2

install_ocudu_gnb:
  stage: install_testbed_2
  interruptible: true
  resource_group: testbed
  needs: [install_srsran_ue]
  script:
    - cd Next_Generation_Node_B
    - ./full_install.sh
    - cd ..
  retry: 2

install_oran_sc_nearrtric:
  stage: install_testbed_2
  interruptible: true
  resource_group: testbed
  needs: [install_ocudu_gnb]
  script:
    - cd RAN_Intelligent_Controllers/Near-Real-Time-RIC
    - ./full_install.sh
    - cd ../..
  retry: 2

install_5gdeploy:
  stage: install_testbed_2
  interruptible: true
  resource_group: testbed
  needs: [install_oran_sc_nearrtric]
  script:
    - cd 5G_Core_Network
    - "sed -i -E 's/^core_to_use:.*/core_to_use: 5gdeploy-oai/' options.yaml"
    - ./full_install.sh
    - cd ..
  retry: 2

configure_srsran_testbed:
  stage: install_testbed_2
  interruptible: true
  resource_group: testbed
  needs: [install_5gdeploy]
  script:
    - "sed -i -E 's/^core_to_use:.*/core_to_use: 5gdeploy-oai/' 5G_Core_Network/options.yaml"
    - ./generate_configurations.sh
  retry: 2

############################ TODO: END-TO-END TESTS ############################

uninstall_open5gs:
  stage: uninstall_testbed_1
  interruptible: true
  resource_group: testbed
  needs:
    - job: configure_srsran_testbed
      optional: true
  when: always
  script:
    - cd 5G_Core_Network
    - "sed -i -E 's/^core_to_use:.*/core_to_use: open5gs/' options.yaml"
    - ./full_uninstall.sh bypass_confirmation
    - cd ..
  retry: 2

uninstall_oai_ue:
  stage: uninstall_testbed_1
  interruptible: true
  resource_group: testbed
  needs:
    - job: uninstall_open5gs
      optional: true
  when: always
  script:
    - cd OpenAirInterface_Testbed/User_Equipment
    - ./full_uninstall.sh bypass_confirmation
    - cd ../..
  retry: 2

uninstall_oai_gnb:
  stage: uninstall_testbed_1
  interruptible: true
  resource_group: testbed
  needs:
    - job: uninstall_oai_ue
      optional: true
  when: always
  script:
    - cd OpenAirInterface_Testbed/Next_Generation_Node_B
    - ./full_uninstall.sh bypass_confirmation
    - cd ../..
  retry: 2

uninstall_flexric:
  stage: uninstall_testbed_1
  interruptible: true
  resource_group: testbed
  needs:
    - job: uninstall_oai_gnb
      optional: true
  when: always
  script:
    - cd OpenAirInterface_Testbed/RAN_Intelligent_Controllers/Flexible-RIC
    - ./full_uninstall.sh bypass_confirmation
    - cd ../../..
  retry: 2

uninstall_srsran_ue:
  stage: uninstall_testbed_2
  interruptible: true
  resource_group: testbed
  needs:
    - job: uninstall_flexric
      optional: true
  when: always
  script:
    - cd User_Equipment
    - ./full_uninstall.sh bypass_confirmation
    - cd ..
  retry: 2

uninstall_ocudu_gnb:
  stage: uninstall_testbed_2
  interruptible: true
  resource_group: testbed
  needs:
    - job: uninstall_srsran_ue
      optional: true
  when: always
  script:
    - cd Next_Generation_Node_B
    - ./full_uninstall.sh bypass_confirmation
    - cd ..
  retry: 2

uninstall_oran_sc_nearrtric:
  stage: uninstall_testbed_2
  interruptible: true
  resource_group: testbed
  needs:
    - job: uninstall_ocudu_gnb
      optional: true
  when: always
  script:
    - cd RAN_Intelligent_Controllers/Near-Real-Time-RIC
    - ./full_uninstall.sh bypass_confirmation
    - cd ../..
  retry: 2

uninstall_5gdeploy:
  stage: uninstall_testbed_2
  interruptible: true
  resource_group: testbed
  needs:
    - job: uninstall_oran_sc_nearrtric
      optional: true
  when: always
  script:
    - cd 5G_Core_Network
    - "sed -i -E 's/^core_to_use:.*/core_to_use: 5gdeploy-oai/' options.yaml"
    - ./full_uninstall.sh bypass_confirmation
    - cd ..
  retry: 2
