stages:
  - pipeline-attempt-1
  - pipeline-attempt-2
  - pipeline-attempt-3

default:
  tags: [testbed-ci-runner]

testbed-ci-runner-1:
  stage: pipeline-attempt-1
  interruptible: true
  trigger:
    include:
      - local: .gitlab-ci.e2e.yml
    strategy: depend
    forward:
      pipeline_variables: true

testbed-ci-runner-2:
  stage: pipeline-attempt-2
  interruptible: true
  when: on_failure
  trigger:
    include:
      - local: .gitlab-ci.e2e.yml
    strategy: depend
    forward:
      pipeline_variables: true

testbed-ci-runner-3:
  stage: pipeline-attempt-3
  interruptible: true
  when: on_failure
  trigger:
    include:
      - local: .gitlab-ci.e2e.yml
    strategy: depend
    forward:
      pipeline_variables: true